name: Setup Dependencies
description: Sets up all the dependencies necessary to build the project.
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Install JS dependencies
      shell: bash
      run: pnpm install

    - name: Install protoc
      shell: bash
      run: sudo apt install -y protobuf-compiler

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install wasm-pack
      shell: bash
      run: cargo install wasm-pack
