syntax = "proto3";

package dmx_controller;

import "proto/color.proto";
import "proto/targeted_effect.proto";

message Pattern {
  uint64 id = 1;
  string name = 2;
  repeated TargetedEffect targeted_effects = 3;
}

message Playlist {
  message Hold { uint64 id = 1; }
  message Sequential {}
  message Shuffle {}

  message Transition {
    uint64 a_id = 1;
    uint64 b_id = 2;
    double blend = 3;

    uint64 start_ms = 4;
    uint64 duration_ms = 5;
  }

  string name = 1;
  repeated Pattern patterns = 2;
  repeated ColorPalette palettes = 3;

  oneof pattern_order {
    Hold pattern_hold = 4;
    Sequential pattern_sequential = 5;
    Shuffle pattern_shuffle = 6;
  }

  oneof palette_order {
    Hold palette_hold = 7;
    Sequential palette_sequential = 8;
    Shuffle palette_shuffle = 9;
  }

  uint32 dwell_ms = 10;
  uint32 transition_ms = 11;

  int64 pattern_offset_ms = 12;
  int64 palette_offset_ms = 13;

  Transition pattern_transition = 14;
  Transition palette_transition = 15;
}
