name: CI

on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/setup

      - name: Generate protobufs
        run: pnpm run proto:generate

      - name: Type check
        run: pnpm run type-check

      - name: Lint TypeScript (ESLint)
        run: pnpm run lint:ts

      - name: Check for dead code (Knip)
        run: pnpm run lint:dead

      - name: Lint Rust (Clippy)
        run: pnpm run lint:rust

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
